<?php

use Illuminate\Database\Seeder;

class CentroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sql = "
        INSERT INTO `centros` (`id`, `empresa_id`, `nombre`, `zona`, `created_at`, `updated_at`) VALUES
		(1, 1, 'POLLOLLO', 1, NULL, NULL),
		(2, 1, 'CALEN 1', 2, NULL, NULL),
		(3, 1, 'PUNTA GRUESA', 1, NULL, NULL),
		(4, 1, 'CALETA SOLEDAD', 1, NULL, NULL),
		(5, 1, 'DUCAÑAS', 2, NULL, NULL),
		(6, 1, 'CHIDHUAPI 1', 1, NULL, NULL),
		(7, 1, 'YELCHO', 2, NULL, NULL),
		(8, 1, 'MANZANO', 1, NULL, NULL),
		(9, 1, 'CHOPE', 1, NULL, NULL),
		(10, 1, 'LORCA', 4, NULL, NULL),
		(11, 1, 'BASE COLO', 2, NULL, NULL),
		(12, 1, 'CALEN 2', 2, NULL, NULL),
		(13, 1, 'ABTAO', 1, NULL, NULL),
		(14, 1, 'TRANQUI 1', 2, NULL, NULL),
		(15, 1, 'TRANQUI 2', 2, NULL, NULL),
		(16, 1, 'QUILEN', 2, NULL, NULL),
		(17, 1, 'CHAULLIN WESTE', 2, NULL, NULL),
		(18, 1, 'AULEN', 1, NULL, NULL),
		(19, 1, 'LINLINAO', 2, NULL, NULL),
		(20, 1, 'CHAUCO', 2, NULL, NULL),
		(21, 1, 'IMELEV', 2, NULL, NULL),
		(22, 1, 'PTO COLO', 1, NULL, NULL),
		(23, 1, 'QUICAVI', 2, NULL, NULL),
		(24, 1, 'RIQUELME', 4, NULL, NULL),
		(25, 1, 'NAVARRO', 4, NULL, NULL),
		(26, 1, 'FURIA', 4, NULL, NULL),
		(27, 1, 'VOIGUE', 2, NULL, NULL),
		(28, 1, 'ISLA TAC', 2, NULL, NULL),
		(29, 1, 'DASERNA', 4, NULL, NULL),
		(30, 1, 'COLACO 4', 1, NULL, NULL),
		(31, 2, 'CAPEHUAPI', 1, NULL, NULL),
		(32, 2, 'CAUCACURA', 2, NULL, NULL),
		(33, 2, 'CHAICAS', 1, NULL, NULL),
		(34, 2, 'CHAUQUEAR', 1, NULL, NULL),
		(35, 2, 'CHIGUAY MAR', 3, NULL, NULL),
		(37, 2, 'DUNCAN', 3, NULL, NULL),
		(38, 2, 'DETICO', 0, NULL, NULL),
		(39, 2, 'ESTEROCOMPU', 2, NULL, NULL),
		(40, 2, 'ISLA PARTIDA', 2, NULL, NULL),
		(41, 2, 'LATOLQUE', 3, NULL, NULL),
		(42, 2, 'LEUTEPU', 2, NULL, NULL),
		(43, 2, 'ISLA MENA', 2, NULL, NULL),
		(44, 2, 'POMPON', 2, NULL, NULL),
		(45, 2, 'QUILLAIPE', 1, NULL, NULL),
		(46, 2, 'SUR ISLOTE', 0, NULL, NULL),
		(47, 3, 'ALAO OESTE', 2, NULL, NULL),
		(48, 3, 'ALAO SUR', 2, NULL, NULL),
		(50, 3, 'BENJAMIN', 0, NULL, NULL),
		(51, 3, 'BUTAN 1', 3, NULL, NULL),
		(52, 3, 'BUTAN 2', 3, NULL, NULL),
		(53, 3, 'BUTAN 7', 3, NULL, NULL),
		(55, 3, 'SAN FRANCISCO', 1, NULL, NULL),
		(56, 3, 'DARWIN 2', 2, NULL, NULL),
		(57, 3, 'RIO NEGRO', 0, NULL, NULL),
		(58, 3, 'HUELDEN', 0, NULL, NULL),
		(59, 3, 'HUENQUILLAHUE', 0, NULL, NULL),
		(61, 3, 'QUITRALCO 1', 3, NULL, NULL),
		(62, 3, 'QUITRALCO 6', 3, NULL, NULL),
		(63, 3, 'QUITRALCO 7', 3, NULL, NULL),
		(64, 3, 'RODADO NOTABLE', 3, NULL, NULL),
		(65, 3, 'SAN FRANCISCO', 1, NULL, NULL),
		(66, 3, 'TORTUGA', 3, NULL, NULL),
		(67, 3, 'VICUÑA 5', 3, NULL, NULL),
		(68, 3, 'YAOTAL', 0, NULL, NULL),
		(69, 3, 'ISLA LARENAS', 3, NULL, NULL),
		(70, 3, 'ISLA LOLA', 3, NULL, NULL),
		(71, 3, 'LEVEL', 3, NULL, NULL),
		(72, 3, 'PULELO', 2, NULL, NULL),
		(73, 3, 'PUNTA COLA', 3, NULL, NULL),
		(74, 3, 'PUNTA REDONDA', 1, NULL, NULL),
		(75, 5, 'MINA ELENA', 0, NULL, NULL),
		(76, 5, 'MIDHURTS', 0, NULL, NULL),
		(77, 5, 'FORSYTH', 0, NULL, NULL),
		(78, 3, 'ASTILLERO', 0, NULL, NULL),
		(79, 3, 'CAMAHUE', 0, NULL, NULL),
		(80, 3, 'PUCHILCO', 0, NULL, NULL),
		(81, 3, 'BUTAN 4', 0, NULL, NULL),
		(82, 1, 'PUNTA DARSENA', 0, NULL, NULL),
		(83, 1, 'PUNTA LAURA', 0, NULL, NULL),
		(84, 1, 'PUNTA LAURA NORTE', 0, NULL, NULL),
		(85, 1, 'CHIDHUAPI 2', 1, NULL, NULL),
		(86, 1, 'QUEMCHI', 1, NULL, NULL),
		(87, 1, 'SUR ESTE', 1, NULL, NULL),
		(88, 1, 'LLANCANCHEO', 1, NULL, NULL),
		(89, 1, 'AGUANTAO', 2, NULL, NULL),
		(90, 1, 'VILUPULLI', 2, NULL, NULL),
		(91, 6, 'MENTIROSA 3', 3, NULL, NULL),
		(92, 2, 'MELIMOYU', 3, NULL, NULL),
		(93, 2, 'ESTEROCOMPU 2', 2, NULL, NULL),
		(94, 2, 'ESTEROCOMPU 3', 2, NULL, NULL),
		(95, 3, 'GARCIA', 3, NULL, NULL),
		(96, 3, 'BOBE', 3, NULL, NULL),
		(97, 3, 'CERES', 3, NULL, NULL),
		(98, 3, 'HUAR SUR', 3, NULL, NULL),
		(99, 3, 'RADA', 2, NULL, NULL),
		(100, 4, 'MATAO', 1, NULL, NULL),
		(101, 4, 'MEULIN', 1, NULL, NULL),
		(102, 4, 'CHILLIDQUE', 1, NULL, NULL),
		(103, 4, 'LIGUAR', 1, NULL, NULL),
		(104, 4, 'LLANCAHUE', 1, NULL, NULL);
		
        ";

        DB::select($sql);
    }
}
